"""new models

Revision ID: 17442cea8db9
Revises: 34aa35bb01fc
Create Date: 2025-06-17 10:29:55.951522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17442cea8db9'
down_revision: Union[str, None] = '34aa35bb01fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='scrape_request_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('processed_games', sa.Integer(), nullable=False),
    sa.Column('successful_scrapes', sa.Integer(), nullable=False),
    sa.Column('failed_scrapes', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('platform_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_requests_id'), 'scrape_requests', ['id'], unique=False)
    op.create_table('game_scrape_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failure', 'not_found', name='scrape_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scrape_request_id', sa.Uuid(), nullable=False),
    sa.Column('scraped_game_data_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_request_id'], ['scrape_requests.id'], ),
    sa.ForeignKeyConstraint(['scraped_game_data_id'], ['scraped_game_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_scrape_details_id'), 'game_scrape_details', ['id'], unique=False)
    op.create_table('scrape_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('successful_scrapes', sa.Integer(), nullable=False),
    sa.Column('failed_scrapes', sa.Integer(), nullable=False),
    sa.Column('not_found', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scrape_metadata', sa.JSON(), nullable=True),
    sa.Column('scrape_request_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['scrape_request_id'], ['scrape_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scrape_request_id')
    )
    op.create_index('idx_scrape_result_platform', 'scrape_results', ['platform_id'], unique=False)
    op.create_index('idx_scrape_result_request', 'scrape_results', ['scrape_request_id'], unique=True)
    op.create_index(op.f('ix_scrape_results_id'), 'scrape_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_results_id'), table_name='scrape_results')
    op.drop_index('idx_scrape_result_request', table_name='scrape_results')
    op.drop_index('idx_scrape_result_platform', table_name='scrape_results')
    op.drop_table('scrape_results')
    op.drop_index(op.f('ix_game_scrape_details_id'), table_name='game_scrape_details')
    op.drop_table('game_scrape_details')
    op.drop_index(op.f('ix_scrape_requests_id'), table_name='scrape_requests')
    op.drop_table('scrape_requests')
    # ### end Alembic commands ###
