"""price_in_usd column

Revision ID: 34aa35bb01fc
Revises: 0d34098537c4
Create Date: 2025-06-15 00:37:57.432953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34aa35bb01fc'
down_revision: Union[str, None] = '0d34098537c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First add the column as nullable
    op.add_column('scraped_game_data', sa.Column('price_in_usd', sa.Float(), nullable=True))
    
    # Set default values for existing rows
    op.execute("""
        UPDATE scraped_game_data 
        SET price_in_usd = CASE 
            WHEN currency = 'USD' THEN price 
            ELSE -1.0 
        END
    """)
    
    # Now alter the column to be NOT NULL
    op.alter_column('scraped_game_data', 'price_in_usd', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_game_data', 'price_in_usd')
    # ### end Alembic commands ###
