"""Regression

Revision ID: 4a59bba119a2
Revises: 5c3100471be0
Create Date: 2025-06-19 00:17:45.048579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a59bba119a2'
down_revision: Union[str, None] = '5c3100471be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('csv_filename', sa.String(length=255), nullable=False),
    sa.Column('dependent_variable', sa.String(length=100), nullable=False),
    sa.Column('independent_variables', sa.JSON(), nullable=False),
    sa.Column('formula', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_requests_id'), 'analysis_requests', ['id'], unique=False)
    op.create_table('regression_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('coefficients_json', sa.JSON(), nullable=False),
    sa.Column('std_errors_json', sa.JSON(), nullable=False),
    sa.Column('t_statistics_json', sa.JSON(), nullable=False),
    sa.Column('p_values_json', sa.JSON(), nullable=False),
    sa.Column('r_squared', sa.Float(), nullable=False),
    sa.Column('adj_r_squared', sa.Float(), nullable=False),
    sa.Column('f_statistic', sa.Float(), nullable=False),
    sa.Column('f_p_value', sa.Float(), nullable=False),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regression_results_id'), 'regression_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regression_results_id'), table_name='regression_results')
    op.drop_table('regression_results')
    op.drop_index(op.f('ix_analysis_requests_id'), table_name='analysis_requests')
    op.drop_table('analysis_requests')
    # ### end Alembic commands ###
