"""Init

Revision ID: 95f34a073f92
Revises: 
Create Date: 2025-06-10 10:15:25.550780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f34a073f92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=150), nullable=False),
    sa.Column('search_url_template', sa.String(length=150), nullable=False),
    sa.Column('game_data_selector', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_platforms_id'), 'platforms', ['id'], unique=False)
    op.create_table('scraped_game_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name_on_platform', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('availability_status', sa.Enum('available', 'out_of_stock', 'coming_soon', 'preorder', 'free', 'unavailable', 'early_access', 'beta', 'region_locked', 'unknown', name='availability_status_enum'), nullable=False),
    sa.Column('url_on_platform', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('search_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('special_content_json', sa.JSON(), nullable=True),
    sa.Column('discount_info_json', sa.JSON(), nullable=True),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_game_data_id'), 'scraped_game_data', ['id'], unique=False)
    op.create_index('ix_unique_game_platform', 'scraped_game_data', ['game_id', 'platform_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_game_platform', table_name='scraped_game_data')
    op.drop_index(op.f('ix_scraped_game_data_id'), table_name='scraped_game_data')
    op.drop_table('scraped_game_data')
    op.drop_index(op.f('ix_platforms_id'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
